#!/usr/bin/env php
<?php

echo "  __  __                                      \n";
echo " |  \/  |                                     \n";
echo " | \  / |  ___  _ __  ___  _   _  _ __  _   _ \n";
echo " | |\/| | / _ \| '__|/ __|| | | || '__|| | | |\n";
echo " | |  | ||  __/| |  | (__ | |_| || |   | |_| |\n";
echo " |_|  |_| \___||_|   \___| \__,_||_|    \__, |\n";
echo "                                         __/ |\n";
echo "                                        |___/ \n";
echo "                                              \n";
echo "Type 'php mercury help <subcommand>' for help on a specific subcommand.\n";
